library(rgeos)
library(raster)
library(maps)
library(ggmap)
library(ggplot2)
library(scales)
library(gridExtra)
library(plyr)
library(cowplot)
library("readxl")

### This plot is further labelled in Powerpoint or Illustrator. The legend colour bar can be generated by changing to show.legend=TRUE in any of the snippets below and shows the average daily number of cases in each month.

data2<-read_excel('SA_provincial_daily_cases.xlsx')

data2$days<-as.Date(cut(data2$date,breaks = "day",start.on.monday = FALSE))
data2$date<-as.Date(cut(data2$date,breaks = "week",start.on.monday = FALSE))
data2$date2<-as.Date(cut(data2$date,breaks = "2 week",start.on.monday = FALSE))

#data2<- data2 %>% filter(Nextstrain_variants!="Other lineages")
#data2<- data2 %>% filter(division!="South Africa")

data2$year = as.numeric(format(data2$date, "%Y"))

data2$month <- factor(format(data2$date, "%B"),
                      levels = month.name)



theme_opts<-list(theme(panel.grid.minor = element_blank(),
                       panel.grid.major = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_blank(),
                       axis.text.x = element_blank(),
                       axis.text.y = element_blank(),
                       axis.ticks = element_blank(),
                       axis.title.x = element_blank(),
                       axis.title.y = element_blank(),
                       plot.title = element_blank(),
                       legend.title=element_text(size=12, face="bold"),
                       legend.text=element_text(size=10)))



SA_original<-getData("GADM", country="ZAF", level=1)
#plot(SA, lwd=0.1, border="black")

#data2[data2=="North-West"]<-"North West"


SA<-SA_original

data3<-subset(data2,year==2020)
data3<-subset(data3,month=='October')

data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_Oct<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1, show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Oct

SA<-SA_original

data3<-subset(data2,year==2020)
data3<-subset(data3,month=='November')

data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")



#plot (fill=n)
p_Delta_Nov<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1, show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Nov


SA<-SA_original

data3<-subset(data2,year==2020)
data3<-subset(data3,month=='December')


data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")



#plot (fill=n)
p_Delta_Dec<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1, show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Dec

SA<-SA_original


data3<-subset(data2,year==2021)
data3<-subset(data3,month=='January')

data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")



#plot (fill=n)
p_Delta_Jan<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1, show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Jan

SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='February')

data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")



#plot (fill=n)
p_Delta_Feb<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Feb

SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='March')

data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")




#plot (fill=n)
p_Delta_March<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma',direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_March


SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='April')

data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")




#plot (fill=n)
p_Delta_April<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1, show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_April

SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='May')

data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")




#plot (fill=n)
p_Delta_May<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1, show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_May

SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='June')

data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")




#plot (fill=n)
p_Delta_June<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_June


SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='July')
data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")



#plot (fill=n)
p_Delta_July<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1, show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
   #        size=0.2) +
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_July


SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='August')
data3<-data3[sapply(data3, is.numeric)]  
df_count<-data.frame(sapply(data3, mean, na.rm = T)) # Returns a vector
df_count

df_count <- cbind(CC_1 = rownames(df_count), df_count)
rownames(df_count) <- 1:nrow(df_count)

colnames(df_count)<-c('CC_1','mean_daily')

pop_data<-read_excel('Provinces popn estimates.xlsx')

df_count<-join(df_count,pop_data, by="CC_1")
df_count

df_count$mean_daily_per_100k<-(df_count$mean_daily/df_count$Population_2021)*100000
df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="CC_1")
SA_df<-join(SA_df,SA@data, by="id")



#plot (fill=n)
p_Delta_August<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=mean_daily_per_100k), size=0.1, show.legend=FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  #scale_fill_viridis_c(option = 'magma', direction=-1,
  scale_fill_viridis_c(option = 'magma', direction=-1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,25,50),labels=c(0,25,50),limits=c(0,50),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_August




plot_grid(p_Delta_Oct,p_Delta_Nov,p_Delta_Dec,p_Delta_Jan,p_Delta_Feb,p_Delta_March,p_Delta_April,p_Delta_May,p_Delta_June,p_Delta_July,p_Delta_August,ncol=11)
