library(rgeos)
library(raster)
library(maps)
library(ggmap)
library(ggplot2)
library(scales)
library(gridExtra)
library(plyr)
library(cowplot)
library("readxl")

### This script generates the prevalence maps for a specified variant or lineage over the specified months (Here October 2020 to August 2021)
### To generate the maps for different variants like in Fig1C, please replace pango_lineage=='C.1.2' in the script snippets below with Nextstrain_clade=='XX' or pango_lineage='XX' with XX being a placeholder for the lineage/variant of your choice as per the data table.
### These maps are further labelled and assembled in Powerpoint or Illustrator. The legend colour bar can be generated by changing to show.legend=TRUE in any of the snippets below and shows the proportion of genomes
### The colour scale can also be changed for each variant by adapting scale_fill_distiller(palette = "YlOrBr",... with any other ggplot brewer palettes


data2<-read_excel('SA_all_data_2Sept_gooddates.xlsx')
data2$days<-as.Date(cut(data2$date,breaks = "day",start.on.monday = FALSE))
data2$date<-as.Date(cut(data2$date,breaks = "week",start.on.monday = FALSE))
data2$date2<-as.Date(cut(data2$date,breaks = "2 week",start.on.monday = FALSE))

#data2<- data2 %>% filter(Nextstrain_variants!="Other lineages")
data2<- data2 %>% filter(division!="South Africa")

data2$year = as.numeric(format(data2$date, "%Y"))

data2$month <- factor(format(data2$date, "%B"),
                      levels = month.name)



theme_opts<-list(theme(panel.grid.minor = element_blank(),
                       panel.grid.major = element_blank(),
                       panel.background = element_blank(),
                       axis.line = element_blank(),
                       axis.text.x = element_blank(),
                       axis.text.y = element_blank(),
                       axis.ticks = element_blank(),
                       axis.title.x = element_blank(),
                       axis.title.y = element_blank(),
                       plot.title = element_blank(),
                       legend.title=element_text(size=12, face="bold"),
                       legend.text=element_text(size=10)))



SA_original<-getData("GADM", country="ZAF", level=1)
#plot(SA, lwd=0.1, border="black")

#data2[data2=="North-West"]<-"North West"


SA<-SA_original

data3<-subset(data2,year==2020)
data3<-subset(data3,month=='October')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_Oct<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1, show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Oct

SA<-SA_original

data3<-subset(data2,year==2020)
data3<-subset(data3,month=='November')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_Nov<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Nov


SA<-SA_original

data3<-subset(data2,year==2020)
data3<-subset(data3,month=='December')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_Dec<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Dec

SA<-SA_original


data3<-subset(data2,year==2021)
data3<-subset(data3,month=='January')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_Jan<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Jan

SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='February')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_Feb<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_Feb

SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='March')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_March<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_March


SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='April')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_April<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_April

SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='May')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_May<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_May

SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='June')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_June<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_June


SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='July')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_July<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
   #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_July


SA<-SA_original

data3<-subset(data2,year==2021)
data3<-subset(data3,month=='August')
data4<-subset(data3,pango_lineage=="C.1.2")

df_count <- data3 %>% count("division")
df_count

#change division to NAME_1
names(df_count)[names(df_count) == "division"] <- "NAME_1"
names(df_count)[names(df_count) == "freq"] <- "Sequences"
df_count

df_count1 <- data4 %>% count("division")
df_count1
names(df_count1)[names(df_count1) == "division"] <- "NAME_1"
names(df_count1)[names(df_count1) == "freq"] <- "Delta"
df_count1

df_count<-merge(df_count,df_count1,by=c("NAME_1"))
df_count

df_count$prev=df_count$Delta/df_count$Sequences

df_count

SA_df<-fortify(SA)


#join with KwaZulu_Natal@data
SA@data$id <- rownames(SA@data)
SA@data<-join(SA@data, df_count, by="NAME_1")
SA_df<-join(SA_df,SA@data, by="id")


#plot (fill=n)
p_Delta_August<-ggplot() + 
  geom_polygon(data=SA_df, aes(long,lat,group=group, fill=prev), size=0.1,show.legend = FALSE)+
  #geom_path(data=SA_df, aes(long,lat, group=group), color="#ffffcc",
  #        size=0.2) +
  scale_fill_distiller(palette = "YlOrBr",limits=c(0,1), direction=1,
                       guide = guide_colourbar(frame.colour = "black", 
                                               ticks.colour = "black", # you can also remove the ticks with NA
                                               barwidth=0.8, barheight=6),
                       breaks=c(0,0.5,1),labels=c(0.0,0.5,1.0),
                       na.value = "grey90")+
  theme(aspect.ratio=1)+theme_opts+
  labs(fill='')
p_Delta_August




plot_grid(p_Delta_Oct,p_Delta_Nov,p_Delta_Dec,p_Delta_Jan,p_Delta_Feb,p_Delta_March,p_Delta_April,p_Delta_May,p_Delta_June,p_Delta_July,p_Delta_August,ncol=11)
